# Generated by Django 2.1.5 on 2022-08-23 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0003_auto_20220823_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='id',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='userType',
        ),
        migrations.RemoveField(
            model_name='client',
            name='id',
        ),
        migrations.RemoveField(
            model_name='client',
            name='paymentMethodId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='planId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
        migrations.AddField(
            model_name='admin',
            name='clients',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admin',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Config.User'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='paymentMethod_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.PaymentMethod'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='plan_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='product_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Config.Product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Config.User'),
            preserve_default=False,
        ),
    ]
