# Generated by Django 4.1 on 2022-08-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0005_auto_20220823_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='clients',
        ),
        migrations.AlterField(
            model_name='productwebsites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
