# Generated by Django 4.1 on 2022-08-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0006_remove_admin_clients_alter_productwebsites_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwordToken',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
