# Generated by Django 2.1.5 on 2022-08-24 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0009_auto_20220824_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Config.UserType'),
        ),
    ]
