# Generated by Django 2.1.5 on 2022-09-08 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0010_auto_20220824_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='paymentNumber',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='client_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Config.Client'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Config.UserType'),
            preserve_default=False,
        ),
    ]
