# Generated by Django 2.1.5 on 2022-09-13 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0011_auto_20220908_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Config.UserType'),
        ),
    ]
