# Generated by Django 4.1.1 on 2022-09-13 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0013_auto_20220913_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productwebsites',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
