# Generated by Django 2.1.5 on 2022-09-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0014_alter_productwebsites_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='favoriteMovie',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='productwebsites',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
