# Generated by Django 2.1.5 on 2022-10-19 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Config', '0015_auto_20220920_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('es', 'Español')], default='en-us', max_length=5),
        ),
    ]
